Fix Android scrolling
GTBitsOfGood/the-ray pull request #116
Opened 2022-03-29 20:08 UTC by luke9kim8

## Fix Android scrolling

Issue Number(s): #106

What does this PR change and why?
* Allows scrolling to work in android
* Fix the issue where the page would scroll too much on one scroll by increasing debounce delay in `onScroll` in `Navigation.js`.

### Checklist

- [x]  Database schema docs have been updated or are not necessary
- [x]  Code follows design and style guidelines
- [x]  Code is commented with doc blocks
- [x]  Tests have been written and executed or are not necessary
- [x]  Latest code has been rebased from base branch (usually `develop`)
- [x]  Commits follow guidelines (concise, squashed, etc)
- [x]  Github issues have been linked in relevant commits
- [x]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### Critical Changes

- None

### Related PRs

- None

### How to Test

1. `npm i; npm run start`
2. Click on either options in the main page
3. Set browser to responsive mode and select some phone (`cmd + option + m` for mac)
4. Try scrolling
5. Try touch scrolling (click and scroll)
6. Bug Luke if it fails

### Potential Future Issues 
1. Scrolling rapidly twice on an actual phone fails to render the animation properly. If scrolls have a 1.5-second delay between one another, it doesn't do this.

2022-04-02 19:46 UTC, kphan32 requested changes
Can u fix this too
![image](https://user-images.githubusercontent.com/73624015/161398836-ac105b69-f401-4682-bdef-e26f1fe3cfc9.png)

2022-04-03 03:53 UTC, luke9kim8 commented
The scrollbar's gone but the removed space becomes an empty space. I didn't fix it bc it's fixed in #118

2022-04-05 23:19 UTC, kphan32 requested changes
It looks like the horizontal scroll is still overflowing
<img width="424" alt="Screen Shot 2022-04-05 at 7 18 04 PM" src="https://user-images.githubusercontent.com/73624015/161866444-d147abd1-30bb-4739-b55d-a0e6a67cb9af.png">

2022-04-10 03:30 UTC, kphan32 approved these changes
lgtm! :+1:

2022-04-10 03:30 UTC, merged