Update Wheelright background image
GTBitsOfGood/the-ray pull request #124
Opened 2022-04-10 23:28 UTC by luke9kim8

## Update Wheelright background image

Issue Number(s): #119 

What does this PR change and why?
* Update Wheelright title screen image with the one they gave us.

### Checklist

- [ ]  Database schema docs have been updated or are not necessary
- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Tests have been written and executed or are not necessary
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### Critical Changes
* I'm always critical

### Related PRs
* N/A

### How to Test
* Check the title screen on mobile and desktop for Wheelright

2022-04-16 00:31 UTC, kphan32 requested changes
why are the images red?
<img width="424" alt="Screen Shot 2022-04-15 at 8 30 54 PM" src="https://user-images.githubusercontent.com/73624015/163654750-cf99e040-f85e-4159-8409-3aa1a746888a.png">

2022-04-16 00:31 UTC, kphan32 commented on src/pages/StartMobile/StartMobileWheelright.js
> +      {/* <img className="start-wheelright-background" src={wheelrightPage1} alt="frontpage" /> */}
remove commented out code pls

2022-04-16 00:31 UTC, kphan32 commented on src/static/css/Start.css
> +  background-image: url('../images/wheelright-background.JPG');
why is the extension capitalized? 🤔

2022-04-25 01:58 UTC, luke9kim8 commented on src/pages/StartMobile/StartMobileWheelright.js
> +      {/* <img className="start-wheelright-background" src={wheelrightPage1} alt="frontpage" /> */}
yuh yuh

2022-04-25 01:58 UTC, luke9kim8 commented on src/static/css/Start.css
> +  background-image: url('../images/wheelright-background.JPG');
changed it

2022-04-28 23:19 UTC, kphan32 approved these changes

2022-04-28 23:19 UTC, merged